### ISSUE TITLE
There is no command for create_candy_machine!

### ISSUE THREAD

**Issue by taimurworks98** [kaizencorps/doorman#2]
There is no command for create_candy_machine, and no candy-machine-cli.ts file in this project, how am I supposed to run this command?

**Comment by hogyzen12** [comment]
you will have to find this out for yourself. It involves using metaplex and the built in candy machine cli there. If you are not comfortable with candy machine, please prioritise that before using doorman! 
any issues with candy machine just ask, but there is a wealth of info avail already on it

**Comment by taimurworks98** [comment]
Yes, I had it figured out yesterday. Forgot to close the issue!
